import streamlit as st
from database import init_db
from auth import register_user, login_user
from categories import save_categories, get_categories
from auth import mark_onboarding_complete
from radar_chart import build_radar_chart
from momentum import submit_daily_checkin
from datetime import date
from time_utils import is_checkin_window_open, get_ist_now
from activity import check_and_apply_missed_days
from activity import mark_app_opened_today, has_checked_in_today
from datetime import date as date_cls
from suggestions import get_top_suggestion
from consistency import get_activity_log,get_current_streak
from charts import build_weekly_pie_chart, build_weekly_bar_chart, build_monthly_line_chart
from analytics import get_weekly_summary, get_daily_scores
from fallback_data import generate_demo_history
from colors import COLOR_PALETTE, DEFAULT_RADAR_COLOR_NAME, DEFAULT_LINE_COLOR_NAME
from background_css import BACKGROUND_CSS


st.set_page_config(page_title="Vector Axis", page_icon="🔺", layout="centered")

st.markdown(BACKGROUND_CSS, unsafe_allow_html=True)

init_db()

if "logged_in" not in st.session_state:
    st.session_state.logged_in = False
if "user" not in st.session_state:
    st.session_state.user = None
if "auth_mode" not in st.session_state:
    st.session_state.auth_mode = "login"


def show_login_page():
    st.title("Vector Axis")

    with st.expander("👀 See how Vector Axis works (no account needed)"):
        st.caption("This is example data generated by the app's own logic - not a real account.")
        demo = generate_demo_history(days=30)

        demo_fig = build_radar_chart(demo["categories"], color=COLOR_PALETTE[DEFAULT_RADAR_COLOR_NAME])
        st.plotly_chart(demo_fig, use_container_width=True, key="preview_radar")

        pie_fig = build_weekly_pie_chart(demo["weekly_summary"][-1])
        st.plotly_chart(pie_fig, use_container_width=True, key="preview_pie")

        bar_fig = build_weekly_bar_chart(demo["weekly_summary"])
        st.plotly_chart(bar_fig, use_container_width=True, key="preview_bar")

        line_fig = build_monthly_line_chart(demo["daily_scores"], line_color=COLOR_PALETTE[DEFAULT_LINE_COLOR_NAME])
        st.plotly_chart(line_fig, use_container_width=True, key="preview_line")

    st.subheader("Log In")

    username = st.text_input("Username", key="login_username")
    password = st.text_input("Password", type="password", key="login_password")

    if st.button("Log In", use_container_width=True):
        success, msg, user = login_user(username, password)
        if success:
            st.session_state.logged_in = True
            st.session_state.user = user
            st.rerun()
        else:
            st.error(msg)

    st.write("Don't have an account?")
    if st.button("Register here", use_container_width=True):
        st.session_state.auth_mode = "register"
        st.rerun()


def show_register_page():
    st.title("Vector Axis")
    st.subheader("Create Account")

    username = st.text_input("Choose a Username", key="reg_username")
    password = st.text_input("Choose a Password", type="password", key="reg_password")
    confirm = st.text_input("Confirm Password", type="password", key="reg_confirm")

    if st.button("Create Account", use_container_width=True):
        if password != confirm:
            st.error("Passwords do not match.")
        else:
            success, msg = register_user(username, password)
            if success:
                st.success(msg + " Please log in.")
                st.session_state.auth_mode = "login"
                st.rerun()
            else:
                st.error(msg)

    st.write("Already have an account?")
    if st.button("Log in here", use_container_width=True):
        st.session_state.auth_mode = "login"
        st.rerun()




def show_onboarding_step1():
    st.title("Set up your Axis")
    st.write("Good + Bad habits must total 10 or less")

    good_count = st.number_input("How many GOOD habits do you want to track?", min_value=0, max_value=10, step=1, key="good_count_input")
    bad_count = st.number_input("How many BAD habits do you want to track?", min_value=0, max_value=10, step=1, key="bad_count_input")

    error_slot = st.empty()

    if st.button("Next", use_container_width=True):
        if good_count + bad_count == 0:
            error_slot.error("Add at least 1 category.")
        elif good_count + bad_count > 10:
            error_slot.error("Good + Bad must be 10 or less.")
        else:
            st.session_state.good_count = int(good_count)
            st.session_state.bad_count = int(bad_count)
            st.session_state.onboarding_step = 2
            st.rerun()


def show_onboarding_step2():
    st.title("Enter what you want to make a habit")

    good_names = []
    for i in range(st.session_state.good_count):
        name = st.text_input(f"Good habit {i + 1}", key=f"good_name_{i}", placeholder="Type a habit name")
        good_names.append(name)

    error_slot = st.empty()

    if st.button("Next", use_container_width=True):
        if any(not n.strip() for n in good_names):
            error_slot.error("Fill in all good habit names.")
        else:
            st.session_state.good_names = good_names
            st.session_state.onboarding_step = 3
            st.rerun()


def show_onboarding_step3():
    st.title("Enter what you want to stop")

    bad_names = []
    for i in range(st.session_state.bad_count):
        name = st.text_input(f"Bad habit {i + 1}", key=f"bad_name_{i}", placeholder="Type a habit name")
        bad_names.append(name)

    error_slot = st.empty()

    if st.button("Finish Setup", use_container_width=True):
        if any(not n.strip() for n in bad_names):
            error_slot.error("Fill in all bad habit names.")
        else:
            save_categories(st.session_state.user["id"], st.session_state.good_names, bad_names)
            mark_onboarding_complete(st.session_state.user["id"])
            st.session_state.user["onboarding_complete"] = True
            st.session_state.onboarding_step = 1  # reset for safety
            st.rerun()
def show_home_page():
    mark_app_opened_today(st.session_state.user["id"])

    st.title("Vector Axis")
    st.write(f"Welcome back, **{st.session_state.user['username']}**!")

    created_date = date_cls.fromisoformat(st.session_state.user["created_at"][:10])
    penalties = check_and_apply_missed_days(st.session_state.user["id"], created_date)
    if penalties > 0:
        st.warning(f"You missed checking in on {penalties} day(s). Your Axis was affected — silence hurts more than an honest bad day.")

    categories = get_categories(st.session_state.user["id"])

    radar_color_name = st.selectbox(
        "Radar color",
        list(COLOR_PALETTE.keys()),
        index=list(COLOR_PALETTE.keys()).index(st.session_state.radar_color_name),
        key="radar_color_select",
    )
    st.session_state.radar_color_name = radar_color_name

    fig = build_radar_chart(categories, color=COLOR_PALETTE[radar_color_name])
    st.plotly_chart(fig, use_container_width=True)

    suggestion = get_top_suggestion(st.session_state.user["id"])
    if suggestion:
        st.markdown("### 🧠 AI Insight")
        if suggestion["mode"] == "heuristic":
            st.info(suggestion["message"])
        else:
            st.warning(suggestion["message"])

    st.write("Raw values (for verification):")
    for cat in categories:
        st.write(f"- **{cat['name']}** ({cat['type']}) — score: {cat['score']:.1f}")

    st.divider()

    if is_checkin_window_open():
        if has_checked_in_today(st.session_state.user["id"]):
            st.success("✅ You've already checked in today. See you tomorrow!")
        else:
            st.success("🟢 Check-in window open (9–11 PM IST)")
            if st.button("Check In for Today", use_container_width=True):
                st.session_state.page = "checkin"
                st.rerun()
    else:
        st.info(f"🔒 View only — check-in opens at 9 PM IST. (Current IST time: {get_ist_now().strftime('%I:%M %p')})")

    if st.button("View Insights (Pie, Bar, Line Charts)", use_container_width=True):
        st.session_state.page = "insights"
        st.rerun()

    if st.button("View Consistency Tracker", use_container_width=True):
        st.session_state.page = "consistency"
        st.rerun()

    if st.button("Log Out"):
        st.session_state.logged_in = False
        st.session_state.user = None
        st.rerun()
def show_checkin_page():
    if not is_checkin_window_open():
        st.error("Check-in is only available between 9 PM and 11 PM IST.")
        if st.button("Back to Axis"):
            st.session_state.page = "home"
            st.rerun()
        return

    if has_checked_in_today(st.session_state.user["id"]):
        st.info("You've already checked in today. Come back tomorrow between 9–11 PM IST.")
        if st.button("Back to Axis"):
            st.session_state.page = "home"
            st.rerun()
        return

    st.title("Today's Check-in")
    st.write("This submission updates your Axis.")

    categories = get_categories(st.session_state.user["id"])
    ticks = {}

    for cat in categories:
        tag = "🟢 Good" if cat["type"] == "good" else "🔴 Bad"
        label = f"{cat['name']} ({tag})"
        ticks[cat["id"]] = st.checkbox(label, key=f"tick_{cat['id']}")

    if st.button("Submit", use_container_width=True):
        submit_daily_checkin(st.session_state.user["id"], ticks)
        st.success("Check-in submitted! Your Axis has been updated.")
        st.session_state.page = "home"
        st.rerun()

def show_consistency_page():
    st.title("Consistency Tracker")

    streak = get_current_streak(st.session_state.user["id"])
    st.metric("Current Streak", f"{streak} day{'s' if streak != 1 else ''}")

    st.write("Last 30 days:")
    log = get_activity_log(st.session_state.user["id"], days_back=30)

    color_map = {
        "submitted": "🟩",
        "opened_no_submit": "⬜",
        "penalty_applied": "🟥",
        None: "⬛",
    }

    # Render as a simple grid, 7 per row (like a calendar week)
    cols_per_row = 7
    for i in range(0, len(log), cols_per_row):
        row = log[i:i + cols_per_row]
        cols = st.columns(cols_per_row)
        for col, entry in zip(cols, row):
            symbol = color_map.get(entry["state"], "⬛")
            col.markdown(f"<div style='text-align:center'>{symbol}<br><small>{entry['date'].strftime('%d/%m')}</small></div>", unsafe_allow_html=True)

    st.caption("🟩 Checked in · 🟥 Missed entirely (penalty applied) · ⬛ No record yet")
    st.write("Missing a day affects your Axis more than an honest bad day would.")

    if st.button("Back to Axis"):
        st.session_state.page = "home"
        st.rerun()



if "onboarding_step" not in st.session_state:
    st.session_state.onboarding_step = 1
if "page" not in st.session_state:
    st.session_state.page = "home"

if "radar_color_name" not in st.session_state:
    st.session_state.radar_color_name = DEFAULT_RADAR_COLOR_NAME
if "line_color_name" not in st.session_state:
    st.session_state.line_color_name = DEFAULT_LINE_COLOR_NAME



def show_insights_page():
    st.title("Insights")

    user_id = st.session_state.user["id"]
    weekly_summary = get_weekly_summary(user_id, weeks_back=5)
    daily_scores = get_daily_scores(user_id, days_back=30)

    # Determine if there's enough real data, or if we should show demo data instead
    has_real_data = any(w["good_count"] + w["bad_count"] > 0 for w in weekly_summary)

    if not has_real_data:
        st.info("📊 No check-in data yet - showing example data so you can see how Insights works. Your real data will replace this as you check in.")
        demo = generate_demo_history(days=30)
        weekly_summary = demo["weekly_summary"]
        daily_scores = demo["daily_scores"]

    # --- Weekly Pie Chart ---
    st.subheader("Weekly Breakdown")
    week_labels = [w["week_start"].strftime("%d %b %Y") for w in weekly_summary]
    selected_label = st.selectbox("Select week", week_labels, index=len(week_labels) - 1)
    selected_week = weekly_summary[week_labels.index(selected_label)]
    pie_fig = build_weekly_pie_chart(selected_week)
    st.plotly_chart(pie_fig, use_container_width=True)

    # --- Weekly Bar Chart ---
    st.subheader("Weekly Performance")
    bar_fig = build_weekly_bar_chart(weekly_summary)
    st.plotly_chart(bar_fig, use_container_width=True)

    # --- Monthly Line Chart ---
    st.subheader("Monthly Trend")
    line_color_name = st.selectbox(
        "Line color",
        list(COLOR_PALETTE.keys()),
        index=list(COLOR_PALETTE.keys()).index(st.session_state.line_color_name),
        key="line_color_select",
    )
    st.session_state.line_color_name = line_color_name
    line_fig = build_monthly_line_chart(daily_scores, line_color=COLOR_PALETTE[line_color_name])
    st.plotly_chart(line_fig, use_container_width=True)

    if st.button("Back to Axis"):
        st.session_state.page = "home"
        st.rerun()


if not st.session_state.logged_in:
    if st.session_state.auth_mode == "login":
        show_login_page()
    else:
        show_register_page()
elif not st.session_state.user["onboarding_complete"]:
    if st.session_state.onboarding_step == 1:
        show_onboarding_step1()
    elif st.session_state.onboarding_step == 2:
        show_onboarding_step2()
    else:
        show_onboarding_step3()
else:
    if st.session_state.page == "checkin":
        show_checkin_page()
    elif st.session_state.page == "consistency":
        show_consistency_page()
    elif st.session_state.page == "insights":
        show_insights_page()
    else:
        show_home_page()
   

